---
Name: System 1
Url: http://localhost/
Prefix: sys2
Database:
    JdbcUrl: jdbc:mysql://localhost/r2r?zeroDateTimeBehavior=convertToNull
    Username: root
    Password: 
    Type: mysql
    Tables: test, test2
    PrimaryKeys: id, id